### ISSUE TITLE
BUG - Error should be thrown if no value is entered and should not allow me to apply the rule.

### ISSUE THREAD

**Issue by georgioajency** [ajency/cashflow-issue-tracker#317]
![image](https://user-images.githubusercontent.com/43877959/78135075-dd6e2900-743e-11ea-93cb-073b2b75c813.png)

![image](https://user-images.githubusercontent.com/43877959/78135239-35a52b00-743f-11ea-9c16-d946fe34fb50.png)

Error message
"Please enter a value"

Also, the input box should be highlighted in Red.

**Comment by robiulpro** [comment]
Fixed

**Comment by TejalBandekar** [comment]
Fixed.

**Comment by TejalBandekar** [comment]
When rule is applied at Total of categories level, no error is being displayed when there isn't any value

**Before applying rule**
![image](https://user-images.githubusercontent.com/45193277/78774815-d604cd80-79b2-11ea-9257-23a018a7baf8.png)


**After applying rule with no value entered**
![image](https://user-images.githubusercontent.com/45193277/78774888-f16fd880-79b2-11ea-86df-425e1b73a775.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by georgioajency** [comment]
I am still getting this issue. It is allowing me to proceed and apply the rule

**Comment by robiulpro** [comment]
Could not replicate, could you please attache snapshot

**Comment by georgioajency** [comment]
Checked. It's working now
