### ISSUE TITLE
BUG - When a planned expense is edited transaction date is not re-indexed

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#537]

**Comment by HazelColaco19** [comment]
Cannot edit the transaction date. Shows an error

![image](https://user-images.githubusercontent.com/55691499/82216650-e061a200-9936-11ea-86d0-aa3f6cfb700f.png)


Network Response: 

{"data":null,"errors":[{"message":"Internal Server Error(s) while executing query","path":null,"extensions":null}]}

Network Header:

![image](https://user-images.githubusercontent.com/55691499/82216615-d344b300-9936-11ea-9ca7-1bd18b2682df.png)

![image](https://user-images.githubusercontent.com/55691499/82216752-08510580-9937-11ea-923f-21f49fd7ed7b.png)

**Comment by legred21** [comment]
input: {id: "27804", company: "45", notify: ["25527", "25534", "25531"], title: "Office rent", amount: "4444",…}
accountingHeadId: "25524"
amount: "4444"
company: "45"
currency: "USD"
description: "Added "
expenseDueDate: "2020-05-28 00:00:00"
expenseRecurrence: {frequency: "yearly", recurrenceEndDate: null, recurrenceMeta: null, __typename: "ExpenseRecurrence"}
frequency: "yearly"
recurrenceEndDate: null
recurrenceMeta: null
__typename: "ExpenseRecurrence"
id: "27804"
notify: ["25527", "25534", "25531"]
0: "25527"
1: "25534"
2: "25531"
paymentStatus: "Paid"
qbCategoryId: 40
recurring: true
tags: ["furniture", "Rents"]
0: "furniture"
1: "Rents"
title: "Office rent"

The Following attribute is invalid in request
__typename: "ExpenseRecurrence"

**Comment by robiulpro** [comment]
Fixed

**Comment by HazelColaco19** [comment]
Tested this on Ajency server, can see the issue still exists

![image](https://user-images.githubusercontent.com/55691499/82294921-81e70300-99cc-11ea-9b79-75f91dccd966.png)


NETWORK:

Response: {"data":null,"errors":[{"message":"Internal Server Error(s) while executing query","path":null,"extensions":null}]}


Header:

Request Payload:

{operationName: "createExpense", variables: {,…},…}
operationName: "createExpense"
query: "mutation createExpense($input: ExpenseInput) {↵  createExpense(input: $input) {↵    id↵    referenceId↵    company {↵      id↵      __typename↵    }↵    accountingHeads {↵      id↵      slug↵      displayName↵      __typename↵    }↵    accountingHead {↵      id↵      __typename↵    }↵    quickbookCategory {↵      id↵      __typename↵    }↵    quickbookCategories {↵      id↵      name↵      __typename↵    }↵    recurring↵    title↵    description↵    notifyUsers {↵      id↵      userMeta {↵        name↵        __typename↵      }↵      __typename↵    }↵    users {↵      id↵      userMeta {↵        name↵        __typename↵      }↵      __typename↵    }↵    amount↵    currency↵    tags↵    expenseTags↵    paymentStatus↵    expenseDueDate↵    expenseRecurrence {↵      frequency↵      recurrenceEndDate↵      recurrenceMeta {↵        forecast {↵          forecastType↵          valueType↵          value↵          __typename↵        }↵        occurrenceCount↵        __typename↵      }↵      __typename↵    }↵    __typename↵  }↵}↵"
variables: {,…}
input: {id: "95660", company: "14", notify: [], title: "Mumbai rent", amount: "769", currency: "USD",…}
accountingHeadId: "131"
amount: "769"
company: "14"
currency: "USD"
description: ""
expenseDueDate: "2020-05-29 00:00:00"
expenseRecurrence: {frequency: "weekly", recurrenceEndDate: "2020-05-22 00:00:00.0", recurrenceMeta: null,…}
frequency: "weekly"
recurrenceEndDate: "2020-05-22 00:00:00.0"
recurrenceMeta: null
__typename: "ExpenseRecurrence"
id: "95660"
notify: []
paymentStatus: "Paid"
qbCategoryId: 65
recurring: true
tags: ["miscellaneous"]
0: "miscellaneous"
title: "Mumbai rent"

**Comment by robiulpro** [comment]
Fixed

**Comment by HazelColaco19** [comment]
Edited date gets reflected for expense db_95660. Can be closed.
