### ISSUE TITLE
BUG - QB data sync fails due to token expiry issue

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#571]
Error Log:

`@version:1 message:2020-05-14 02:05:54,379 ERROR com.intuit.oauth2 [task-53] Exception while calling refreshToken com.intuit.oauth2.exception.OAuthException: failed getting access token at com.intuit.oauth2.client.OAuth2PlatformClient.refreshToken(OAuth2PlatformClient.java:140) at com.toppeq.cashflow.service.QuickBooksService.getUpdatedAccessToken(QuickBooksService.java:1294) at com.toppeq.cashflow.service.CompanyCashServiceImpl.getProfitAndLossData(CompanyCashServiceImpl.java:427`

**Comment by nutank** [comment]
This is happening way too frequently now.

**Comment by robiulpro** [comment]
@nutank @HazelColaco19 
Fixed and deployed on staging.

**Comment by HazelColaco19** [comment]
Tested in two places:

1. Company cash table > " quickbook_closing_cash_balance " values were non zero.
2. The  quickbook_closing_cash_balance in Forecast template as well is non zero.

To be tested in 24 hours, ticket to be monitored.

**Comment by robiulpro** [comment]
Added 'last_token_refreshed' column in company_quickbook_accounts table to keep track of refresh token. In every 20 hours the token should get refreshed to avoid expiry of refresh token.

**Comment by HazelColaco19** [comment]
Fixed. Works now

**Comment by nutank** [comment]
The issue still persists. last_token_refreshed date is not getting updated on UAT server.

**Comment by legred21** [comment]
![image](https://user-images.githubusercontent.com/55079454/85519478-30f7a980-b61f-11ea-8a47-fbec587b2818.png)

Fixed by updating token after every 40 minutes
