### ISSUE TITLE
BUG - Category: Accounts Receivable has 3 missing records that could be displayed on the Table

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#609]
**Current Behavior:**

3 Missing records  are highlighted in red in the image. They are not displayed on the toppeq side

Here are the details:

1. Transaction Type = Payment  , QBParentID = 413

Timestamp in milliseconds: 1587513600000

The record seems to be missing from kibana @legred21 

There should have been an OUTFLOW value = 367 INR

![image](https://user-images.githubusercontent.com/55691499/81400919-c8766b00-914b-11ea-8a22-a19a6b114699.png)

2. Transaction Type = Payment , QBParentID = 418

This is not present in Kibana. Data needs to be fetched @legred21
![image](https://user-images.githubusercontent.com/55691499/81400640-38382600-914b-11ea-9a35-2d7893edc0d9.png)

3. Transaction Type = Payment  , QBParentID = 454

Timestamp in milliseconds: 1588636800000

This entry is available in Kibana, so needs to be displayed on Toppeq side. @robiulpro 
![image](https://user-images.githubusercontent.com/55691499/81400392-96183e00-914a-11ea-95cc-4453ec8650ca.png)
However the " CASHFLOW type " field is displayed wrong. It says " Inflow " when it should have been " Outflow' @legred21 

![image](https://user-images.githubusercontent.com/55691499/81399103-0b364400-9148-11ea-9c3b-5d3a9141f0f7.png)

**Comment by legred21** [comment]
**Transaction Type = Payment , QBParentID = 413**
Entry present in elastic
![image](https://user-images.githubusercontent.com/55079454/81403234-93204c00-9150-11ea-899b-0c06651584e3.png)

**Transaction Type = Payment , QBParentID = 418**
No line items present and hence won't get indexed
![image](https://user-images.githubusercontent.com/55079454/81403326-c5ca4480-9150-11ea-9368-92121bd743ce.png)

**Transaction Type = Payment , QBParentID = 454**
Entry present in elastic
![image](https://user-images.githubusercontent.com/55079454/81403473-180b6580-9151-11ea-99e0-b5bb6658e8b0.png)

**Comment by robiulpro** [comment]
Lets pick this as hotfix as it might take little longer to find and fix.

**Comment by robiulpro** [comment]
Fixed

**Comment by HazelColaco19** [comment]
QBParentID = 454 is still not displayed on toppeq side @robiulpro 

![image](https://user-images.githubusercontent.com/55691499/81951553-eb5cbf80-9622-11ea-8e04-3b9beef2d008.png)


@legred21 Th mapping for this has disapeared

![image](https://user-images.githubusercontent.com/55691499/81951608-016a8000-9623-11ea-9d2e-9f141f520703.png)
