### ISSUE TITLE
TASK - A-53 - While projection is created, past data should be only till last month not current month

### ISSUE THREAD

**Issue by nutank** [ajency/cashflow-issue-tracker#654]

**Comment by nutank** [comment]
@robiulpro - change created date of projection to one month minus current month.

**Comment by robiulpro** [comment]
Done

**Comment by HazelColaco19** [comment]
Not fixed. 

While creation it shows past data till May 2020, 
![image](https://user-images.githubusercontent.com/55691499/83517558-b2638c80-a4f6-11ea-9124-e91042c18dfb.png)


but later post creation the current month falls in past data

![image](https://user-images.githubusercontent.com/55691499/83517574-b8f20400-a4f6-11ea-8266-ec0f612c3bbc.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by HazelColaco19** [comment]
While creating a projection cannot select " June " ( current month ) as the future projection. It takes in the input only if you choose July and further


![image](https://user-images.githubusercontent.com/55691499/83634640-7ac11700-a5c0-11ea-8c2d-7c77052cf9c9.png)

**Comment by robiulpro** [comment]
Current month shouldn't selectable, it's a feature.

**Comment by HazelColaco19** [comment]
Can be closed
