### ISSUE TITLE
BUG - Cannot upload the CSV file while creation of a projection. It validates or sends a message saying " Not a CSV " when a CSV is being uploaded.

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#717]
Cannot upload the CSV file while creation of a projection. It validates or sends a message saying " Not a CSV " when a CSV is being uploaded.

File in Question: [Link](https://drive.google.com/open?id=1Fu0W1CEOJ19YhNPWs_DMat4DB2veQL0Z)

![image](https://user-images.githubusercontent.com/55691499/82640450-3d57a380-9c28-11ea-90ef-e0912af0b9e0.png)

**Comment by robiulpro** [comment]
@HazelColaco19 
As discussed, duplicate category issue has been fixed. Also make sure to define date range based on past and future of projection.

**Comment by HazelColaco19** [comment]
Does not look fixed. still get the same error

**Comment by robiulpro** [comment]
Fixed.

**Comment by HazelColaco19** [comment]
Still cannot upload. Noticed the months in the sheet are from jan 2019 to june 2020, when it should have gone up til december 2020


![image](https://user-images.githubusercontent.com/55691499/83014114-c103fc80-a03b-11ea-802e-6272ccd0e70c.png)

**Comment by HazelColaco19** [comment]
@nutank I could successfully create a projection using a different Windows system, id of which is 121431. I have used the same CSV that was failing on my system.

**Comment by HazelColaco19** [comment]
As discussed, we can close this issue.
