### ISSUE TITLE
BUG - Deleted expense stays on forecast template post UPDATE

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/cashflow-issue-tracker#723]
company = 65

**DETAILS OF EXPENSE:**

qb id = 28 , Amount = 500, Date = 5 May 2020

**qbAccountCategory | toppeqCategory | toppeqActivityType**

Bank Charges & Fees    |    Operating Outflow - Others     |   Operating

**Current behavior:**

The expense was deleted from QB and post sync, it disapeared from Kibana and also Cashflow table.
Then on Update of template, the delete value still remained

![image](https://user-images.githubusercontent.com/55691499/82817583-dc93c980-9eba-11ea-9cfd-c9aac43ca8eb.png)

**Comment by legred21** [comment]
Fixed cashflow delete query

**Comment by HazelColaco19** [comment]
Currently can still see past entries that were deleted even re-sync or update.

![image](https://user-images.githubusercontent.com/55691499/82900122-acf7c680-9f79-11ea-926b-ecb7227b4afd.png)


To be tested with fresh delete.

**Comment by HazelColaco19** [comment]
Fixed
